// src/components/Navigation.vue
<template>
  <nav class="p-menubar">
    <div class="flex items-center justify-between max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16">
      <div class="flex items-center">
        <a href="/" class="text-2xl font-bold text-primary">FZB Emlak</a>
      </div>
      <div class="hidden md:block">
        <div class="ml-10 flex items-baseline space-x-4">
          <a href="/" class="text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium">Ana Sayfa</a>
          <a href="/projeler" class="text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium">Projeler</a>
          <a href="/lokasyonlar" class="text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium">Lokasyonlar</a>
          <a href="/hakkimizda" class="text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium">Hakkımızda</a>
          <a href="/iletisim" class="text-gray-700 hover:text-primary px-3 py-2 rounded-md text-sm font-medium">İletişim</a>
        </div>
      </div>
      <div class="md:hidden">
        <Button icon="pi pi-bars" @click="toggleMenu" />
        <Menu ref="menu" :model="items" :popup="true" />
      </div>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import Button from 'primevue/button'
import Menu from 'primevue/menu'

const menu = ref()
const items = [
  { label: 'Ana Sayfa', icon: 'pi pi-home', url: '/' },
  { label: 'Projeler', icon: 'pi pi-building', url: '/projeler' },
  { label: 'Lokasyonlar', icon: 'pi pi-map-marker', url: '/lokasyonlar' },
  { label: 'Hakkımızda', icon: 'pi pi-info-circle', url: '/hakkimizda' },
  { label: 'İletişim', icon: 'pi pi-envelope', url: '/iletisim' }
]

const toggleMenu = (event: Event) => {
  menu.value?.toggle(event)
}
</script>

<style scoped>
.p-menubar {
  background-color: white;
  border: none;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  position: sticky;
  top: 0;
  z-index: 1000;
}
</style>

// app/components/Navigation.tsx
import { useState } from 'react';
import Link from 'next/link';
import { motion, AnimatePresence } from 'framer-motion';
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline';

const navigation = [
  { name: 'Ana Sayfa', href: '/' },
  { name: 'Projeler', href: '/projeler' },
  { name: 'Lokasyonlar', href: '/lokasyonlar' },
  { name: 'Yatırım Fırsatları', href: '/yatirim' },
  { name: 'Hakkımızda', href: '/hakkimizda' },
  { name: 'İletişim', href: '/iletisim' },
];

export default function Navigation() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <header className="fixed w-full bg-white/90 backdrop-blur-md z-50">
      <nav className="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
        <div className="flex lg:flex-1">
          <Link href="/" className="-m-1.5 p-1.5">
            <span className="text-2xl font-bold text-blue-600">FZB Emlak</span>
          </Link>
        </div>
        <div className="flex lg:hidden">
          <button
            type="button"
            className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
            onClick={() => setMobileMenuOpen(true)}
          >
            <span className="sr-only">Ana menüyü aç</span>
            <Bars3Icon className="h-6 w-6" aria-hidden="true" />
          </button>
        </div>
        <div className="hidden lg:flex lg:gap-x-12">
          {navigation.map((item) => (
            <Link
              key={item.name}
              href={item.href}
              className="text-sm font-semibold leading-6 text-gray-900 hover:text-blue-600 transition-colors"
            >
              {item.name}
            </Link>
          ))}
        </div>
        <div className="hidden lg:flex lg:flex-1 lg:justify-end">
          <Link
            href="/iletisim"
            className="bg-blue-600 text-white px-4 py-2 rounded-full text-sm font-semibold hover:bg-blue-700 transition-colors"
          >
            Bize Ulaşın
          </Link>
        </div>
      </nav>

      <AnimatePresence>
        {mobileMenuOpen && (
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="lg:hidden"
            role="dialog"
            aria-modal="true"
          >
            <div className="fixed inset-0 z-50">
              <div className="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
                <div className="flex items-center justify-between">
                  <Link href="/" className="-m-1.5 p-1.5">
                    <span className="text-2xl font-bold text-blue-600">FZB Emlak</span>
                  </Link>
                  <button
                    type="button"
                    className="-m-2.5 rounded-md p-2.5 text-gray-700"
                    onClick={() => setMobileMenuOpen(false)}
                  >
                    <span className="sr-only">Menüyü kapat</span>
                    <XMarkIcon className="h-6 w-6" aria-hidden="true" />
                  </button>
                </div>
                <div className="mt-6 flow-root">
                  <div className="-my-6 divide-y divide-gray-500/10">
                    <div className="space-y-2 py-6">
                      {navigation.map((item) => (
                        <Link
                          key={item.name}
                          href={item.href}
                          className="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
                          onClick={() => setMobileMenuOpen(false)}
                        >
                          {item.name}
                        </Link>
                      ))}
                    </div>
                    <div className="py-6">
                      <Link
                        href="/iletisim"
                        className="block w-full bg-blue-600 text-white px-4 py-2 rounded-full text-center text-sm font-semibold hover:bg-blue-700 transition-colors"
                        onClick={() => setMobileMenuOpen(false)}
                      >
                        Bize Ulaşın
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </header>
  );
}
