// app/components/Footer.tsx
import Link from 'next/link';

const navigation = {
  main: [
    { name: 'Ana Sayfa', href: '/' },
    { name: 'Projeler', href: '/projeler' },
    { name: 'Lokasyonlar', href: '/lokasyonlar' },
    { name: 'Yatırım Fırsatları', href: '/yatirim' },
    { name: 'Hakkımızda', href: '/hakkimizda' },
    { name: 'İletişim', href: '/iletisim' },
  ],
  projects: [
    { name: 'Yeni Projeler', href: '/projeler/yeni' },
    { name: 'Tamamlanan Projeler', href: '/projeler/tamamlanan' },
    { name: 'Yakında Başlayacak', href: '/projeler/yakinda' },
  ],
  locations: [
    { name: 'Avrupa Yakası', href: '/lokasyonlar/avrupa' },
    { name: 'Anadolu Yakası', href: '/lokasyonlar/anadolu' },
    { name: 'Popüler Bölgeler', href: '/lokasyonlar/populer' },
  ],
  social: [
    {
      name: 'Facebook',
      href: '#',
      icon: (props: any) => (
        <svg fill="currentColor" viewBox="0 0 24 24" {...props}>
          <path
            fillRule="evenodd"
            d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
            clipRule="evenodd"
          />
        </svg>
      ),
    },
    {
      name: 'Instagram',
      href: '#',
      icon: (props: any) => (
        <svg fill="currentColor" viewBox="0 0 24 24" {...props}>
          <path
            fillRule="evenodd"
            d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z"
            clipRule="evenodd"
          />
        </svg>
      ),
    },
    {
      name: 'Twitter',
      href: '#',
      icon: (props: any) => (
        <svg fill="currentColor" viewBox="0 0 24 24" {...props}>
          <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84" />
        </svg>
      ),
    },
  ],
};

export default function Footer() {
  return (
    <footer className="bg-gray-900" aria-labelledby="footer-heading">
      <h2 id="footer-heading" className="sr-only">
        Footer
      </h2>
      <div className="mx-auto max-w-7xl px-6 pb-8 pt-16 sm:pt-24 lg:px-8 lg:pt-32">
        <div className="xl:grid xl:grid-cols-3 xl:gap-8">
          <div className="space-y-8">
            <Link href="/" className="text-2xl font-bold text-white">
              FZB Emlak
            </Link>
            <p className="text-sm leading-6 text-gray-300">
              İstanbul'un en prestijli konut projelerinde güvenilir yatırım fırsatları.
            </p>
            <div className="flex space-x-6">
              {navigation.social.map((item) => (
                <Link key={item.name} href={item.href} className="text-gray-500 hover:text-gray-400">
                  <span className="sr-only">{item.name}</span>
                  <item.icon className="h-6 w-6" aria-hidden="true" />
                </Link>
              ))}
            </div>
          </div>
          <div className="mt-16 grid grid-cols-2 gap-8 xl:col-span-2 xl:mt-0">
            <div className="md:grid md:grid-cols-2 md:gap-8">
              <div>
                <h3 className="text-sm font-semibold leading-6 text-white">Projeler</h3>
                <ul role="list" className="mt-6 space-y-4">
                  {navigation.projects.map((item) => (
                    <li key={item.name}>
                      <Link href={item.href} className="text-sm leading-6 text-gray-300 hover:text-white">
                        {item.name}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
              <div className="mt-10 md:mt-0">
                <h3 className="text-sm font-semibold leading-6 text-white">Lokasyonlar</h3>
                <ul role="list" className="mt-6 space-y-4">
                  {navigation.locations.map((item) => (
                    <li key={item.name}>
                      <Link href={item.href} className="text-sm leading-6 text-gray-300 hover:text-white">
                        {item.name}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-16 border-t border-white/10 pt-8 sm:mt-20 lg:mt-24">
          <p className="text-xs leading-5 text-gray-400">
            &copy; {new Date().getFullYear()} FZB Emlak. Tüm hakları saklıdır.
          </p>
        </div>
      </div>
    </footer>
  );
}

// src/components/Footer.vue
<template>
  <footer class="footer">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        <!-- Company Info -->
        <div class="col-span-1">
          <img src="/logo.png" alt="FZB İnşaat" class="h-8 w-auto mb-4" />
          <p class="text-gray-400 text-sm">
            20 yılı aşkın tecrübemizle İstanbul'un en değerli lokasyonlarında yaşam alanları inşa ediyoruz.
          </p>
          <div class="mt-4 flex space-x-4">
            <a href="#" class="text-gray-400 hover:text-primary">
              <i class="pi pi-facebook"></i>
            </a>
            <a href="#" class="text-gray-400 hover:text-primary">
              <i class="pi pi-twitter"></i>
            </a>
            <a href="#" class="text-gray-400 hover:text-primary">
              <i class="pi pi-instagram"></i>
            </a>
            <a href="#" class="text-gray-400 hover:text-primary">
              <i class="pi pi-linkedin"></i>
            </a>
          </div>
        </div>

        <!-- Quick Links -->
        <div class="col-span-1">
          <h3 class="text-white font-semibold mb-4">Hızlı Bağlantılar</h3>
          <ul class="space-y-2">
            <li v-for="link in quickLinks" :key="link.text">
              <a :href="link.href" class="text-gray-400 hover:text-primary">{{ link.text }}</a>
            </li>
          </ul>
        </div>

        <!-- Projects -->
        <div class="col-span-1">
          <h3 class="text-white font-semibold mb-4">Projelerimiz</h3>
          <ul class="space-y-2">
            <li v-for="project in projects" :key="project.text">
              <a :href="project.href" class="text-gray-400 hover:text-primary">{{ project.text }}</a>
            </li>
          </ul>
        </div>

        <!-- Contact -->
        <div class="col-span-1">
          <h3 class="text-white font-semibold mb-4">İletişim</h3>
          <ul class="space-y-4">
            <li class="flex items-start">
              <i class="pi pi-map-marker text-primary mt-1 mr-2"></i>
              <span class="text-gray-400">Ataşehir, İstanbul<br />Türkiye</span>
            </li>
            <li class="flex items-center">
              <i class="pi pi-phone text-primary mr-2"></i>
              <span class="text-gray-400">+90 (216) 123 45 67</span>
            </li>
            <li class="flex items-center">
              <i class="pi pi-envelope text-primary mr-2"></i>
              <span class="text-gray-400">info@fzbinsaat.com</span>
            </li>
          </ul>
        </div>
      </div>

      <div class="mt-12 pt-8 border-t border-gray-700">
        <div class="text-center text-gray-400 text-sm">
          <p>&copy; {{ new Date().getFullYear() }} FZB İnşaat. Tüm hakları saklıdır.</p>
        </div>
      </div>
    </div>
  </footer>
</template>

<script setup lang="ts">
const quickLinks = [
  { text: 'Ana Sayfa', href: '/' },
  { text: 'Hakkımızda', href: '/about' },
  { text: 'Projeler', href: '/projects' },
  { text: 'Lokasyonlar', href: '/locations' },
  { text: 'İletişim', href: '/contact' },
]

const projects = [
  { text: 'Yeni Fikirtepe', href: '/projects/fikirtepe' },
  { text: 'Residence Inn Deluxia', href: '/projects/deluxia' },
  { text: 'Kiptaş Kartal', href: '/projects/kartal' },
  { text: 'Tüm Projeler', href: '/projects' },
]
</script>

<style scoped>
.footer {
  background-color: #1a1a1a;
  color: white;
}

.text-primary {
  color: var(--primary-color);
}

a {
  transition: color 0.2s ease-in-out;
}

.pi {
  font-size: 1.25rem;
}
</style>
